//
//  CityWeatherViewControllerTests.swift
//  Weather
//
//  Created by Anuwat Sittichak on 21/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Weather
import XCTest

class CityWeatherViewControllerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: CityWeatherViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupCityWeatherViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupCityWeatherViewController() {
        sut = StoryboardScene.CityWeather.cityWeatherViewController.instantiate()
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    class CityWeatherBusinessLogicSpy: CityWeatherBusinessLogic, CityWeatherDataStore {
        var keyword: String = ""
        var degree: Degree = .celsius
        var selectDegreeCalled = false
        var getCurrentWeatherCalled = false
        
        func selectDegree(request: CityWeatherModels.SelectDegree.Request) {
            selectDegreeCalled = true
        }
        
        func getCurrentWeather(request: CityWeatherModels.GetCurrentWeather.Request) {
            getCurrentWeatherCalled = true
        }
    }
    
    // MARK: Tests
    
    func testChangeDegreeShouldAskInteractorToSetSelectDegree() {
        // Given
        let interactorSpy = CityWeatherBusinessLogicSpy()
        sut.interactor = interactorSpy
        
        // When
        sut.loadView()
        sut.degreeSegmentedControl.selectedSegmentIndex = 1
        sut.segmentedControlValueChanged(sut.degreeSegmentedControl)
        
        // Then
        XCTAssert(interactorSpy.selectDegreeCalled, "change degree should ask interactor to SetSelectDegree()")
    }
    
    func testSearchCityNameShouldAskInteractorToGetCurrentWeather() {
        // Given
        let interactorSpy = CityWeatherBusinessLogicSpy()
        sut.interactor = interactorSpy
        
        // When
        sut.loadView()
        sut.cityNameTextField.text = "test"
        _ = sut.textFieldShouldReturn(sut.cityNameTextField)
        
        // Then
        XCTAssert(interactorSpy.getCurrentWeatherCalled, "search city name should ask interactor to getCurrentWeather()")
    }
}
