//
//  ForecastInteractor.swift
//  Weather
//
//  Created by Anuwat Sittichak on 18/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForecastBusinessLogic {
    func doSomething(request: ForecastModels.Something.Request)
}

protocol ForecastDataStore {
    //var name: String { get set }
}

final class ForecastInteractor: ForecastBusinessLogic, ForecastDataStore {
    var presenter: ForecastPresentationLogic?
    var worker: ForecastWorker?
    //var name: String = ""
  
    // MARK: Do something
  
    func doSomething(request: ForecastModels.Something.Request) {
        worker = ForecastWorker()
        worker?.doSomeWork()
        
        let response = ForecastModels.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
