//
//  ForecastModels.swift
//  Weather
//
//  Created by Anuwat Sittichak on 18/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct ForecastModels {
    // MARK: Use cases
  
    struct GetForecast {
        struct Request {
        
        }
    
        struct Response {
            let result: UserResult<[CurrentWeather]>
        }
        
        struct ViewModel {
            let content: Content<[DisplayForecast]>
        }
    }
    
    struct DisplayForecast {
        let date: String
        let time: String
        let iconUrl: URL?
        let highTemp: Double
        let lowTemp: Double
        
        init(date: String, time: String, iconUrl: URL?, highTemp: Double, lowTemp: Double) {
            self.date = date
            self.time = time
            self.iconUrl = iconUrl
            self.highTemp = highTemp
            self.lowTemp = lowTemp
        }
    }
}
