//
//  ForecastInteractor.swift
//  Weather
//
//  Created by Anuwat Sittichak on 18/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForecastBusinessLogic {
    func getForecast(request: ForecastModels.GetForecast.Request)
}

protocol ForecastDataStore {
    var keyword: String { get set }
}

final class ForecastInteractor: ForecastBusinessLogic, ForecastDataStore {
    var keyword: String = ""
    
    var presenter: ForecastPresentationLogic?
    var weatherWorker: WeatherWorker?
    
    func getForecast(request: ForecastModels.GetForecast.Request) {
        let data = GetForecastRequestData(q: keyword)
        typealias Response = ForecastModels.GetForecast.Response
        var response: Response
        response = Response(result: UserResult.loading)
        presenter?.presentForecast(response: response)
        weatherWorker?.getForecast(data: data, completion: { [weak self] (result) in
            switch result {
            case .success(let data):
                response = Response(result: UserResult.success(result: data))
            case .failure(let error):
                response = Response(result: UserResult.failure(userError: error))
            }
            self?.presenter?.presentForecast(response: response)
        })
    }
}
