//
//  ForecastPresenter.swift
//  Weather
//
//  Created by Anuwat Sittichak on 18/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForecastPresentationLogic {
    func presentSomething(response: ForecastModels.Something.Response)
}

final class ForecastPresenter: ForecastPresentationLogic {
    weak var viewController: ForecastDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ForecastModels.Something.Response) {
        let viewModel = ForecastModels.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
