//
//  ForecastRouter.swift
//  Weather
//
//  Created by Anuwat Sittichak on 18/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ForecastRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

final class ForecastRouter: NSObject, ForecastRoutingLogic {
    weak var viewController: ForecastViewController?
    var dataStore: ForecastDataStore?
    
    // MARK: Routing
    
    // func routeToSomewhere(segue: UIStoryboardSegue?) { }
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: ForecastViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: ForecastDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
