//
//  ForecastPresenterTests.swift
//  Weather
//
//  Created by Anuwat Sittichak on 21/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Weather
import XCTest

class ForecastPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: ForecastPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupForecastPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupForecastPresenter() {
        sut = ForecastPresenter()
    }
    
    // MARK: Test doubles
    
    class ForecastDisplayLogicSpy: ForecastDisplayLogic {
        var displayForecastCalled = false
        
        func displayForecast(viewModel: ForecastModels.GetForecast.ViewModel) {
            displayForecastCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentForecastShouldAskViewControllerToDisplayForecast() {
        // Given
        let viewControllerSpy = ForecastDisplayLogicSpy()
        sut.viewController = viewControllerSpy
        
        // When
        let weatherList: [CurrentWeather] = []
        let data = ("", weatherList)
        let result = UserResult.success(result: data)
        let response = ForecastModels.GetForecast.Response(result: result)
        sut.presentForecast(response: response)
        
        // Then
        XCTAssert(viewControllerSpy.displayForecastCalled, "presentForecast() should ask viewController to displayForecast()")
    }
}
