//
//  ForecastViewControllerTests.swift
//  Weather
//
//  Created by Anuwat Sittichak on 21/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Weather
import XCTest

class ForecastViewControllerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: ForecastViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupForecastViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupForecastViewController() {
        sut = StoryboardScene.Forecast.forecastViewController.instantiate()
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    class ForecastBusinessLogicSpy: ForecastBusinessLogic, ForecastDataStore {
        var keyword: String = ""
        var degree: Degree = .celsius
        var getForecastCalled = false
        
        func getForecast(request: ForecastModels.GetForecast.Request) {
            getForecastCalled = true
        }
    }
    
    // MARK: Tests
    
    func testViewDidLoadShouldAskInteractorToGetForecast() {
        // Given
        let interactorSpy = ForecastBusinessLogicSpy()
        sut.interactor = interactorSpy
        
        // When
        sut.loadView()
        sut.viewDidLoad()
        
        // Then
        XCTAssert(interactorSpy.getForecastCalled, "viewDidLoad() should ask interactor to getForecast()")
    }
}
