//
//  ForecastInteractorTests.swift
//  Weather
//
//  Created by Anuwat Sittichak on 21/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Weather
import XCTest

class ForecastInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: ForecastInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupForecastInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupForecastInteractor() {
        sut = ForecastInteractor()
    }
    
    // MARK: Test doubles
    
    class ForecastPresentationLogicSpy: ForecastPresentationLogic {
        var presentForecastCalled = false
        
        func presentForecast(response: ForecastModels.GetForecast.Response) {
            presentForecastCalled = true
        }
    }
    
    // MARK: Tests
    
    func testGetForecastShouldAskPresenterToPresentForecast() {
        // Given
        let presenterSpy = ForecastPresentationLogicSpy()
        sut.presenter = presenterSpy
        
        // When
        let request = ForecastModels.GetForecast.Request()
        sut.getForecast(request: request)
        
        // Then
        XCTAssert(presenterSpy.presentForecastCalled, "getForecast() should ask presenter to presentForecast()")
    }
}
