//
//  CityWeatherInteractor.swift
//  Weather
//
//  Created by Anuwat Sittichak on 18/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityWeatherBusinessLogic {
    func doSomething(request: CityWeatherModels.Something.Request)
}

protocol CityWeatherDataStore {
    //var name: String { get set }
}

final class CityWeatherInteractor: CityWeatherBusinessLogic, CityWeatherDataStore {
    var presenter: CityWeatherPresentationLogic?
    var worker: CityWeatherWorker?
    //var name: String = ""
  
    // MARK: Do something
  
    func doSomething(request: CityWeatherModels.Something.Request) {
        worker = CityWeatherWorker()
        worker?.doSomeWork()
        
        let response = CityWeatherModels.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
