//
//  CityWeatherModels.swift
//  Weather
//
//  Created by Anuwat Sittichak on 18/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct CityWeatherModels {
    // MARK: Use cases
  
    struct GetCurrentWeather {
        struct Request {
            let cityName: String
        }
    
        struct Response {
            let result: UserResult<CurrentWeather>
        }
        
        struct ViewModel {
            let content: Content<CurrentWeather>
        }
    }
}
