//
//  CityWeatherPresenter.swift
//  Weather
//
//  Created by Anuwat Sittichak on 18/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityWeatherPresentationLogic {
    func presentSomething(response: CityWeatherModels.Something.Response)
}

final class CityWeatherPresenter: CityWeatherPresentationLogic {
    weak var viewController: CityWeatherDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: CityWeatherModels.Something.Response) {
        let viewModel = CityWeatherModels.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
