//
//  CityWeatherModels.swift
//  Weather
//
//  Created by Anuwat Sittichak on 18/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct CityWeatherModels {
    // MARK: Use cases
  
    struct SelectDegree {
        struct Request {
            let degree: Degree
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    struct GetCurrentWeather {
        struct Request {
            let cityName: String
        }
    
        struct Response {
            let result: UserResult<CurrentWeather>
        }
        
        struct ViewModel {
            let content: Content<DisplayWeather>
        }
    }
    
    struct DisplayWeather {
        let name: String
        let description: String
        let imageUrl: URL?
        let temp: String
        let humidity: String
        
        init(name: String, description: String, imageUrl: URL?, temp: String, humidity: String) {
            self.name = name
            self.description = description
            self.imageUrl = imageUrl
            self.temp = temp
            self.humidity = humidity
        }
    }
}
