//
//  CityWeatherViewController.swift
//  Weather
//
//  Created by Anuwat Sittichak on 18/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityWeatherDisplayLogic: class {
    func displayCurrentWeather(viewModel: CityWeatherModels.GetCurrentWeather.ViewModel)
}

final class CityWeatherViewController: BaseViewController, CityWeatherDisplayLogic {
    var interactor: (CityWeatherBusinessLogic & CityWeatherDataStore)?
    var router: (NSObjectProtocol & CityWeatherRoutingLogic)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = CityWeatherInteractor()
        let presenter = CityWeatherPresenter()
        let router = CityWeatherRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.weatherWorker = WeatherWorker(store: WeatherRestStore())
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }
    
    private func setupUI() {
        forecastButton.isHidden = true
        detailView.isHidden = true
        noResultView.isHidden = true
        cityNameTextField.delegate = self
    }
    
    // MARK: IBOutlet
    @IBOutlet var forecastButton: UIButton!
    @IBOutlet var cityNameTextField: UITextField!
    @IBOutlet var cityNameLabel: UILabel!
    @IBOutlet var tempLabel: UILabel!
    @IBOutlet var humidityLabel: UILabel!
    @IBOutlet var descriptionLabel: UILabel!
    @IBOutlet var detailView: UIView!
    @IBOutlet var noResultView: UIView!
    
    // MARK: IBAction
    @IBAction func viewForecast(_ sender: UIButton) {
        router?.navigateToForecast()
    }
    
    // MARK: Function
    
    private func getCurrentWeather(cityName: String) {
        let request = CityWeatherModels.GetCurrentWeather.Request(cityName: cityName)
        interactor?.getCurrentWeather(request: request)
    }
    
    // MARK: Display
    
    func displayCurrentWeather(viewModel: CityWeatherModels.GetCurrentWeather.ViewModel) {
        switch viewModel.content {
        case .success(let data):
            cityNameLabel.text = data.name
            descriptionLabel.text = unwrapped(data.weather.first?.description, with: "")
            tempLabel.text = "\(data.main.temp)°C"
            humidityLabel.text = "\(data.main.humidity)%"
            forecastButton.isHidden = false
            detailView.isHidden = false
            noResultView.isHidden = true
            hideIndicator()
        case .userError:
            forecastButton.isHidden = true
            detailView.isHidden = true
            noResultView.isHidden = false
            hideIndicator()
        case .loading:
            showIndicator()
        default:
            break
        }
    }
}

extension CityWeatherViewController: UITextFieldDelegate {
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        let text = unwrapped(textField.text, with: "")
        view.endEditing(true)
        getCurrentWeather(cityName: text)
        return true
    }
}
