//
//  CityWeatherViewController.swift
//  Weather
//
//  Created by Anuwat Sittichak on 18/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityWeatherDisplayLogic: class {
    func displaySomething(viewModel: CityWeatherModels.Something.ViewModel)
}

final class CityWeatherViewController: BaseViewController, CityWeatherDisplayLogic {
    var interactor: (CityWeatherBusinessLogic & CityWeatherDataStore)?
    var router: (NSObjectProtocol & CityWeatherRoutingLogic)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = CityWeatherInteractor()
        let presenter = CityWeatherPresenter()
        let router = CityWeatherRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: IBOutlet
    @IBOutlet var nameTextField: UITextField!
    
    // MARK: IBAction
    @IBAction func openForecast(_ sender: UIButton) {
        router?.navigateToForecast()
    }
    
    // MARK: Function
    
    func doSomething() {
        let request = CityWeatherModels.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    // MARK: Display
    
    func displaySomething(viewModel: CityWeatherModels.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
