//
//  CityWeatherPresenter.swift
//  Weather
//
//  Created by Anuwat Sittichak on 18/4/2563 BE.
//  Copyright (c) 2563 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityWeatherPresentationLogic {
    func presentSelectDegree(response: CityWeatherModels.SelectDegree.Response)
    func presentCurrentWeather(response: CityWeatherModels.GetCurrentWeather.Response)
}

final class CityWeatherPresenter: CityWeatherPresentationLogic {
    weak var viewController: CityWeatherDisplayLogic?
    
    func presentSelectDegree(response: CityWeatherModels.SelectDegree.Response) {
        let viewModel = CityWeatherModels.SelectDegree.ViewModel()
        viewController?.displaySelectDegree(viewModel: viewModel)
    }
    
    func presentCurrentWeather(response: CityWeatherModels.GetCurrentWeather.Response) {
        typealias ViewModel = CityWeatherModels.GetCurrentWeather.ViewModel
        var viewModel: ViewModel
        switch response.result {
        case .success(let data):
            let name = data.name
            let description = unwrapped(data.weather.first?.description, with: "")
            let imageUrl = URL(string: APIClient.share.getImagePath(icon: unwrapped(data.weather.first?.icon, with: "")))
            let temp = "\(data.main.temp)°"
            let humidity = "\(data.main.humidity)%"
            let displayWeather = CityWeatherModels.DisplayWeather(name: name, description: description, imageUrl: imageUrl, temp: temp, humidity: humidity)
            viewModel = ViewModel(content: Content.success(data: displayWeather))
        case .failure(let error):
            viewModel = ViewModel(content: Content.userError(error))
        case .loading:
            viewModel = ViewModel(content: Content.loading)
        }
        viewController?.displayCurrentWeather(viewModel: viewModel)
    }
}
